#!/bin/sh
#Write a shell script that deletes all lines containing a specified word in one or more files supplied as arguments to it.

if [ $# -eq 0 ]
then
        echo "usage: <arg>"
        exit 0
fi

echo "enter a word"
read word
for file in $*
do
        sed "/$word/d" $file | tee tmp
        mv tmp $file
done
