#!/bin/sh
#write a shell script to find the factorial of a number.
echo "enter number"
read num
fact=1
while [ $num -gt 1 ]
do
        fact=$((fact \* num))
        num=$((num-1))
done
        echo "$fact"