#!/bin/sh
# hello world in Bold and blink and also in different colours red, green blue , brown ..etc
echo "\e[1m Hello world"
echo "\e[31m Hello world"
echo "\e[32m Hello world"
echo "\e[33m Hello world"
echo "\e[34m Hello world"
echo "\e[5m Hello world"
