#!/bin/sh
#Write a network monitor application server_monitor.sh which show the below information

#OS name
#Architecture version
#Kernel version
#Internet status
#IP Address
#Memory Usage
#Disk file systems usage
#system uptime

ping -c 4 www.google.com > /dev/null 2> /dev/null
if [ $? -eq 0 ]
then
        echo "Network status:internet connected"
else
        echo "internet disconnected"
        exit 0
fi

echo kernel version: `uname -r`
echo ip address: `hostname -I`
echo Architecture version: `arch`
echo OS name: `uname -o`
echo Disc usage: `du -sh`
echo System uptime: `uptime`
